### ISSUE TITLE
Add Support for Windows 10 21H2

### ISSUE THREAD

**Issue by nomukuk** [microsoft/MSLab#473]
Why do you have support for 22H2 support
but not for 21H2

**Comment by jaromirk** [comment]
Very good question :). It's because 20H1,20H2 and 21H1 have for some reason the same setup.exe file (same version) with build number of 20H1. So the script is unable to detect what version it is. In theory it could by mounting wim before asking for name. But since it's for name only, you can simply provide whatever media you want and then specify custom name or rename vhd after it's created. 

Makes sense?

**Comment by jaromirk** [comment]
This is the code that's responsible for grabbing version https://github.com/microsoft/MSLab/blob/master/Tools/CreateParentDisk.ps1#L109

**Comment by jaromirk** [comment]
It's not a bug, it's a feature 😏
