### ISSUE TITLE
Question: Whats the difference between MSLab and WSLab

### ISSUE THREAD

**Issue by Karl-WE** [microsoft/MSLab#492]
Hello @jaromirk
can you answer me what the difference between this project [microsoft/MSLab](https://github.com/microsoft/MSLab/issues/new) and [microsoft/WSLab] (https://github.com/jaromirk/WSLab).
Thank you!

**Comment by jaromirk** [comment]
haha, good one! There was a history of renaming. First release was WS2016Lab (when Windows Server 2016 was released). Then I renamed it to WSLab (when Windows Server 2019 was released) and then I renamed it to MSLab when Azure Stack HCI was released. Makes sense? :). The link is just old fork...

**Comment by Mrkuff** [comment]
Ahaha you had to call it DreamLab instead!! Man, I've found you just yesterday and the scénario stuff are crazy!   I was "just" looking for a WACGW template best practice and end with a fully automatic CA template creation!!  I need to hook up with you guy!    
I've work on Ian Farr ADMirror PS script in 2016 (https://www.powershellgallery.com/packages/ADMirror/1.0) who's take a xml "backup" of all the object in AD.  It's a suite of script you run like this:

	First you dump the config in XML files (and GPO backup)
1-	Dump_OU_Structure 
2-	Dump_Users 
3-	Dump_Groups 
4-	BackUp_GPOs   
and then you Mirror it in another AD
1-	Mirror_OU_Structure
2-	Mirror_Users
3-	Mirror_Groups
4-	Import_GPOs

But the scripts were incomplete because the rights on "restored" GPO and OU were blank! And I've worked on those script and we were able to "dump" a production AD entirely in XML file/GPO backup and then "restore" it in a blank LAB AD.. *the only issue was with the   [Microsoft.GroupPolicy.GPPermissionType]::GpoCustom right on GPO.  GpoCustom don't really give you the right assignation… I don't know if they fixed this since in Get-GPPermissions cmdlet*

But, they scraped the project at my work because they find it too dangerous to use!!  Being able to backup the production outside of the traditional channel was a nightmare! Ahah  me I was just looking to a way for a quick Production snap for testing purpose offline..

I can share my script with you guys!

**Comment by jaromirk** [comment]
@Mrkuff  you should also check this one https://github.com/davidprowe/BadBlood ... Nice way to create "production-like looking" AD :)

**Comment by jaromirk** [comment]
@Mrkuff and btw. I started to write some easier hands-on-labs for Azure Stack HCI - also worth checking https://github.com/DellGEOS/AzureStackHOLs ...

**Comment by Mrkuff** [comment]
BadBlood isnt like a random Domain creation?

**Comment by Mrkuff** [comment]
Oh... AD-Clone service it's a sold product.. oops

**Comment by Mrkuff** [comment]
Wanna me to try to create a "Mirroir AD from one Domain to another" Scenario ?

**Comment by jaromirk** [comment]
Maybe :). You can deploy MSLab, populate AD with BadBlood, export, redeploy MSLab and import :)
