### ISSUE TITLE
Powerpoint files show wrong url?

### ISSUE THREAD

**Issue by jfmatth** [microsoft/MSLab#539]
Hi, I love this project, thank you!

I downloaded your slides from OneDrive and they all point to MSLab, yet all your slides say WSlab?

Not sure if that's an issue you want to fix, just pointing it out :)

Again, love the repo!

**Comment by machv** [comment]
Hello,
good catch :-) WSLab was initial name Jaromir chose when primary focus of this tool was deploying Windows (Server) based labs, but since Azure Stack HCI has been released we've decided to change the name to MSLab to better position this tool that Microsoft based labs can be created with this tool.

But all the links should still be working and are kept up to date.

**Comment by jfmatth** [comment]
Yes all the links work, but the name is wrong, and completely threw me off for bit.

Great project

**Comment by machv** [comment]
@jaromirk, maybe time for a content refresh then? ;-)

**Comment by jaromirk** [comment]
Well, these PPTs are from presentations I delivered (when it was still WSLab :). I do maintain step by step walktroughs here https://geos.to/azslabs

**Comment by jaromirk** [comment]
I also work on docs here: https://github.com/DellGEOS/AzureStackDocs

**Comment by Karl-WE** [comment]
Seems like PPT is completely removed @jfmatth #close ?
