### ISSUE TITLE
Poor Documentation for Scenarios

### ISSUE THREAD

**Issue by yusufozturk** [microsoft/MSLab#570]
Hi,

First of all, what a great project, especially for the automation of Azure Stack HCI. As a retired PowerShell MVP, I love the work.

I would like to bring attention to some of the documentation issues. I am sure that when you are used to the project, you don't notice UX issues. However, it's very difficult to understand how to run Scenarios. The entire documentation is geared towards the Hydration phase and preparation, but then there is no / or minimal information on how to run Scenarios. There are LabConfig files, but they seem to represent config differences rather than the main LabConfig files and that is not clear. There is no indication that scenarios should be run on the DC server. So, the warming-up part is very easy to understand, but the Scenario part remains a mystery. I think the main reason might be that the scenarios were made by other people/teams.

I was able to deploy Azure Stack HCI after reading the documentation here, as the docs were not helpful:
https://learn.microsoft.com/en-us/azure-stack/hci/deploy/tutorial-private-forest

I think you should add more explanation for beginners who want to try this lab.

As I said, now that I understand the logic of the project, installing/reinstalling scenarios is very easy for me. It saves a lot of time. Thanks again.

Yusuf

**Comment by Karl-WE** [comment]
Hi @yusufozturk I can certainly see your point and appreciate your feedback. not speaking on behalf of Jaromir here. There is a kind of gap but if you understand how to use the scenario files things get clear. 
Jaromir and me recently had a talk about how community calls could help to make this amazing project even better and more accessible while also trying to get some work off for Jaromir. My idea what to restructure some parts and avoid duplicates, because code changes happen and over the course there are different iterations and versions of steps that do no longer align with the lastest code, plus it is not feasible for Jaromir to update them one by one.

If you haven't yet feel free to join the Azure Slack HCI community to broaden the ideas about this.

**Comment by jaromirk** [comment]
I did create introduction hands on labs here: https://github.com/DellGEOS/AzureStackHOLs. Does it help?
